/// Flutter icons ComoGastoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ComoGastoIcons
///      fonts:
///       - asset: fonts/ComoGastoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ComoGastoIcons {
  ComoGastoIcons._();

  static const _kFontFam = 'ComoGastoIcons';

  static const IconData camera = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData pie_chart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData stats_bars = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe806, fontFamily: _kFontFam);
}
